# version: "3"

# services:
#   web:
#     build: .
#     ports:
#       - "8000:8000"
#     volumes:
#       - .:/app
#     environment:
#       - DEBUG=True
version: '3.9'

services:
  web:
    build: .
    container_name: startup-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8000
